- name: Configure HQ-RTR Alt Server
  hosts: HQ-SRV
  become: true
  tasks:
    - name: Set hostname
      hostname:
        name: HQ-SRV

    - name: Configure DNS nameserver
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 8.8.8.8"
        create: true

    - name: Create network_admin user
      user:
        name: network_admin
        password: "{{ 'P@ssw0rd' | password_hash('sha512') }}"
        groups: root,wheel
        append: true

    - name: Create admin user
      user:
        name: admin
        password: "{{ 'P@ssw0rd' | password_hash('sha512') }}"
        groups: root,wheel
        append: true

    - name: Configure SSH access
      lineinfile:
        path: /etc/openssh/sshd_config
        line: "AllowUsers *@11.11.11.0/26 *@55.55.55.0/28 *@22.22.22.0/30 *@44.44.44.0/30"
        create: true

    - name: Reboot the system
      reboot:
        msg: "Rebooting system to apply changes"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
