- name: Provision Samba AD DC on HQ-SRV
  hosts: hq-srv
  become: yes
  tasks:
    - name: Установить необходимые пакеты
      package:
        name:
          - samba
          - samba-dc
          - samba-dsdb-modules
          - samba-client
          - krb5-workstation
        state: present

    - name: Удалить существующий smb.conf
      file:
        path: /etc/samba/smb.conf
        state: absent

    - name: Provision Samba AD DC
      expect:
        command: samba-tool domain provision
          cmd: "samba-tool domain provision --realm=HQ.WORK --domain=HQ --adminpass=P@ssw0rd --dns-backend=SAMBA_INTERNAL --server-role=dc --option='dns forwarder=8.8.8.8'"

    - name: Включить и запустить службу Samba AD DC
      systemd:
        name: samba-ad-dc
        enabled: yes
        state: started
