---
- name: Полная установка Moodle на ALT Server
  hosts: BR-SRV
  become: true

  vars_prompt:
    - name: "mysql_root_password"
      prompt: "Введите пароль root для MySQL"
      private: yes
    - name: "moodle_db_password"
      prompt: "Введите пароль для пользователя Moodle"
      private: yes

  vars:
    moodle_version_url: https://download.moodle.org/latest.zip
    moodle_dir: /var/www/moodle
    moodle_data_dir: /var/www/moodledata
    moodle_db_name: moodle
    moodle_db_user: moodleuser
    moodle_admin_user: admin
    moodle_admin_pass: P@ssw0rd
    moodle_admin_email: admin@hq-srv.hq.work

  tasks:

    - name: Включение и запуск служб
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - mysqld
        - httpd2

    - name: Создание базы данных Moodle
      community.mysql.mysql_db:
        name: "{{ moodle_db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Создание пользователя базы данных Moodle
      community.mysql.mysql_user:
        name: "{{ moodle_db_user }}"
        password: "{{ moodle_db_password }}"
        priv: "{{ moodle_db_name }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Загрузка Moodle
      get_url:
        url: "{{ moodle_version_url }}"
        dest: /tmp/moodle.zip

    - name: Распаковка Moodle
      unarchive:
        src: /tmp/moodle.zip
        dest: /var/www/
        remote_src: yes

    - name: Создание директории moodledata
      file:
        path: "{{ moodle_data_dir }}"
        state: directory
        owner: apache
        group: apache
        mode: '0770'

    - name: Установка прав на директории Moodle
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: apache
        group: apache
      loop:
        - "{{ moodle_dir }}"
        - "{{ moodle_data_dir }}"

    - name: Установка Moodle через CLI
      command: >
        /usr/bin/php {{ moodle_dir }}/admin/cli/install.php
        --chmod=2770
        --lang=ru
        --wwwroot=http://{{ ansible_fqdn }}/moodle
        --dataroot={{ moodle_data_dir }}
        --dbtype=mysqli
        --dbhost=localhost
        --dbname={{ moodle_db_name }}
        --dbuser={{ moodle_db_user }}
        --dbpass={{ moodle_db_password }}
        --fullname="My Moodle"
        --shortname="moodle"
        --adminuser={{ moodle_admin_user }}
        --adminpass={{ moodle_admin_pass }}
        --adminemail={{ moodle_admin_email }}
        --non-interactive
        --agree-license
      args:
        creates: "{{ moodle_dir }}/config.php"

    - name: Перезапуск Apache
      systemd:
        name: httpd2
        state: restarted
