- name: Вставка XML volume-блока в pam_mount.conf.xml
  hosts: BR-SRV
  become: yes
  vars:
    samba_shares_block: |
      [Branch_Files]
        path = /opt/branch
        writable = yes
        read only = no
        valid users = @"HQ\\Branch admins"

      [Network]
        path = /opt/network
        writable = yes
        read only = no
        valid users = @"HQ\\Network admins"

      [Admin_Files]
        path = /opt/admin
        writable = yes
        read only = no
        valid users = @"HQ\\Admins"
      
      system_auth_block: |
        session		[success=1 default=ignore] pam_succeed_if.so service = systemd-user quiet
        session		optional	pam_mount.so disable_interactive
  tasks:
    - name: Вставить блок конфигурации в smb.conf
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {mark} ANSIBLE MANAGED SMB SHARES BLOCK"
        block: "{{ samba_shares_block }}"
        insertafter: EOF

    - name: Установка пакетов
      ansible.builtin.package:
        name:
        - pam_mount
        - cifs-utils
        - systemd-settings-enable-kill-user-processes
        state: present

    - name: Reboot the system
      reboot:
        msg: "Rebooting system to apply changes"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
        
    - name: Вставить блок конфигурации в smb.conf
      ansible.builtin.blockinfile:
        path: /etc/pam.d/system-auth
        marker: "# {mark} ANSIBLE MANAGED SYS-AUT SHARES BLOCK"
        block: "{{ system_auth_block }}"
        insertafter: EOF 
        
    - name: Вставить блок volume definitions
      ansible.builtin.blockinfile:
        path: /etc/security/pam_mount.conf.xml
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        insertafter: '^\s*<!-- Volume definitions -->\s*$'
        block: |
          <volume uid="Admin"
              fstype="cifs"
              server="hq-srv.hq.work"
              path="Admin_Files"
              mountpoint="/mnt/All_files"
              options="sec=krb5i,cruid=%(USERUID),nounix,uid=%(USERUID),gid=%(USERGID),file_mode=0664,dir_mode=0775"/>
          <volume uid="Network admin"
              fstype="cifs"
              server="hq-srv.hq.work"
              path="Network"
              mountpoint="/mnt/All_files"
              options="sec=krb5i,cruid=%(USERUID),nounix,uid=%(USERUID),gid=%(USERGID),file_mode=0664,dir_mode=0775"/>
          <volume uid="Branch admin"
              fstype="cifs"
              server="hq-srv.hq.work"
              path="Branch_Files"
              mountpoint="/mnt/All_files"
              options="sec=krb5i,cruid=%(USERUID),nounix,uid=%(USERUID),gid=%(USERGID),file_mode=0664,dir_mode=0775"/>
